name: test-send-build-info

on:
  workflow_dispatch:

jobs:
  send-build-info:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Send CodeLogic Build Info
        uses: ./.github/actions/codelogic-send-build-info@feature/CAPE-8816_create_github_action
        with:
          codelogic_host: https://thingsboard.app.codelogic.com
          agent_uuid: 519802da-a504-4f36-b672-40c03ab474f4
          agent_password: n12rP7XVm3TJlwtO
          scan_path: /github/workspace
          job_name: github-action-test-abacio
          build_number: 2
          build_status: FINGERS-CROSSED
          pipeline_system: GitHub-Actions
          verbose: "true"
          dry_run: "true"   # remove after wiring looks good
